export const EROSION = "Erosion";
export const DILATION = "Dilation";
export const THRESHOLD = "Threshold";
export const INTERPOLATION = 'Interpolation';
export const MEDIAN = 'Median';
export const GAUSSIAN = 'Gaussian';
export const SUBSTRACT_IMAGE = 'Substract Image';
export const YOLO = "Yolo";
export const BICUBIC_INTERPOLATION = 'Bicubic Interpolation';